- name: "Install Dask"
    pip:
      name: dask
      executable: pip3

- name: "Install Pandas"
    pip:
      name: pandas
      executable: pip3

- name: "Install Faust"
    pip:
      name: faust
      executable: pip3